version: '3.8'

# Development environment with hot-reload and database integration
# Usage: docker-compose -f docker-compose.dev.yml up
# Requires: .env file (copy from .env.example)

services:
  # API Gateway with hot reload
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
      target: builder
    image: mbuaku/cloudmastershub-backend:dev
    volumes:
      - ./services/api-gateway/src:/app/services/api-gateway/src
      - ./shared:/app/shared
    command: npm run dev --workspace=@cloudmastershub/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - COURSE_SERVICE_URL=http://course-service:3002
      - LAB_SERVICE_URL=http://lab-service:3003
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      - user-service
      - course-service
      - lab-service
    networks:
      - cloudmastershub

  # User Service with hot reload
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
      target: builder
    image: mbuaku/cloudmastershub-backend:dev
    volumes:
      - ./services/user-service/src:/app/services/user-service/src
      - ./shared:/app/shared
    command: npm run dev --workspace=@cloudmastershub/user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=15m
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=30d
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - BCRYPT_ROUNDS=10
    depends_on:
      - postgres
      - redis
    networks:
      - cloudmastershub

  # Course Service with hot reload
  course-service:
    build:
      context: .
      dockerfile: services/course-service/Dockerfile
      target: builder
    image: mbuaku/cloudmastershub-backend:dev
    volumes:
      - ./services/course-service/src:/app/services/course-service/src
      - ./shared:/app/shared
    command: npm run dev --workspace=@cloudmastershub/course-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3002
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    depends_on:
      - mongodb
      - redis
    networks:
      - cloudmastershub

  # Lab Service with hot reload
  lab-service:
    build:
      context: .
      dockerfile: services/lab-service/Dockerfile
      target: builder
    image: mbuaku/cloudmastershub-backend:dev
    volumes:
      - ./services/lab-service/src:/app/services/lab-service/src
      - ./shared:/app/shared
    command: npm run dev --workspace=@cloudmastershub/lab-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MAX_LAB_DURATION=3600
      - MAX_CONCURRENT_LABS=100
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    depends_on:
      - redis
    networks:
      - cloudmastershub

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - cloudmastershub

  # MongoDB Database
  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    networks:
      - cloudmastershub

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - cloudmastershub

  # Adminer for database management
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - cloudmastershub

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    depends_on:
      - redis
    networks:
      - cloudmastershub

networks:
  cloudmastershub:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data: