# CloudMastersHub Secrets Configuration
# IMPORTANT: This file contains base64-encoded example values
# In production, use proper secret management tools (Vault, Sealed Secrets, etc.)
# 
# To generate base64 values: echo -n "your-value" | base64
# To decode base64 values: echo "encoded-value" | base64 -d

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudmastershub-secrets
  namespace: cloudmastershub-dev
  labels:
    app: cloudmastershub
    environment: dev
type: Opaque
data:
  # PostgreSQL credentials
  # cloudmaster | base64
  postgres-user: Y2xvdWRtYXN0ZXI=
  # cloudmaster123 | base64
  postgres-password: Y2xvdWRtYXN0ZXIxMjM=
  # cloudmastershub_users | base64
  postgres-database: Y2xvdWRtYXN0ZXJzaHViX3VzZXJz
  
  # MongoDB credentials
  # cloudmaster | base64
  mongodb-username: Y2xvdWRtYXN0ZXI=
  # cloudmaster123 | base64
  mongodb-password: Y2xvdWRtYXN0ZXIxMjM=
  # cloudmastershub_courses | base64
  mongodb-database: Y2xvdWRtYXN0ZXJzaHViX2NvdXJzZXM=
  # admin | base64
  mongodb-auth-source: YWRtaW4=
  
  # Redis configuration
  # (empty string for no password) | base64
  redis-password: ""
  
  # JWT secrets
  # your-jwt-secret-key-change-in-production-minimum-32-characters | base64
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1taW5pbXVtLTMyLWNoYXJhY3RlcnM=
  # your-refresh-token-secret-change-in-production-minimum-32-chars | base64
  refresh-token-secret: eW91ci1yZWZyZXNoLXRva2VuLXNlY3JldC1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1taW5pbXVtLTMyLWNoYXJz
  
  # AWS credentials (for S3 and lab provisioning)
  # your-access-key-change-in-production | base64
  aws-access-key-id: eW91ci1hY2Nlc3Mta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  # your-secret-key-change-in-production | base64
  aws-secret-access-key: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  # us-east-1 | base64
  aws-region: dXMtZWFzdC0x
  # cloudmastershub-videos | base64
  aws-s3-bucket: Y2xvdWRtYXN0ZXJzaHViLXZpZGVvcw==
  
  # Encryption keys
  # cloudmastershub-encryption-key-minimum-32-characters | base64
  encryption-key: Y2xvdWRtYXN0ZXJzaHViLWVuY3J5cHRpb24ta2V5LW1pbmltdW0tMzItY2hhcmFjdGVycw==
  
  # API keys
  # cloudmastershub-internal-api-key-2024 | base64
  internal-api-key: Y2xvdWRtYXN0ZXJzaHViLWludGVybmFsLWFwaS1rZXktMjAyNA==

---
# Database connection strings secret
apiVersion: v1
kind: Secret
metadata:
  name: cloudmastershub-db-urls
  namespace: cloudmastershub-dev
  labels:
    app: cloudmastershub
    environment: dev
type: Opaque
stringData:
  # PostgreSQL connection string
  postgres-url: "postgresql://cloudmaster:cloudmaster123@postgres.cloudmastershub-dev.svc.cluster.local:5432/cloudmastershub_users"
  
  # MongoDB connection string
  mongodb-uri: "mongodb://cloudmaster:cloudmaster123@mongodb.cloudmastershub-dev.svc.cluster.local:27017/cloudmastershub_courses?authSource=admin"
  
  # Redis connection string
  redis-url: "redis://redis.cloudmastershub-dev.svc.cluster.local:6379"

---
# Docker registry secret template
# Create this secret using:
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=your-dockerhub-username \
#   --docker-password=your-dockerhub-password \
#   --docker-email=your-email@example.com \
#   -n cloudmastershub-dev