-- CloudMastersHub Payment Service
-- Migration 005: Update Stripe Price IDs with real values
-- Run Date: 2025-01-27
-- Status: DEPRECATED - Superseded by migration 008 (live Stripe account)
--
-- This migration contained IDs from old Stripe account (acct BDGO3PHkIg).
-- All Stripe IDs are now managed via migration 008 using live account (acct Bej8Yb7psW).
-- Kept as historical record only. Do NOT re-run.